Feature/4
horba/my-trip pull request #14
Opened 2020-05-09 14:44 UTC by valerachuk

2020-05-10 21:04 UTC, horba requested changes

2020-05-10 21:04 UTC, horba commented on front/src/styles/common.css
> +.auth-form{
all css rules related to login form should be placed in styles of login view

2020-05-10 21:04 UTC, horba commented on front/src/views/LoginCard.vue
> +<template>
it is really big view code, espetially when you add styles, so it is more compact to separate template, js code and styles

2020-05-10 21:04 UTC, horba commented on front/src/styles/common.css
> +  line-height: 125%;
why do you use percentage?

2020-05-10 21:04 UTC, horba commented on front/src/styles/common.css
> +.auth-card {
if default view of components needs changes to be up to design and these changes will be actual for view of this component in different views it is better to place in common rules to prevent duplication of css

2020-05-10 21:04 UTC, horba commented on front/src/styles/common.css
> +  color: #273B7A;
ira left link in channel how to customise error text color

2020-05-10 21:04 UTC, horba commented on front/src/styles/common.css
> +  color: #F44336;
please, check if it is actual after theme changes in dev

it seems like it is common rules not only for login

if it is some type of primary color it should be created css variables in variables.css and use it in other places

2020-05-10 21:04 UTC, horba commented on front/src/main.js
>  import Default from './layouts/Default.vue';
please, add @layout path and use it like

import { Default, Authorize } from '@layout'

2020-05-10 21:04 UTC, horba commented on front/src/router/index.js
>  } from '@views';
please, change import one component per line onto several to save vertical space in component

2020-05-11 12:52 UTC, valerachuk commented on front/src/styles/common.css
> +  line-height: 125%;
Just copied this property from figma...
Should I delete it ?

2020-05-12 00:51 UTC, valerachuk commented on front/src/styles/common.css
> +.auth-card {
it is already in common.css ...

2020-05-12 17:23 UTC, horba approved these changes

2020-05-12 17:23 UTC, merged